language: c
before_install:
- sudo apt-get update -q
install:
- sudo apt-get install -qq lib32z1
script:
  - cd g2core
  - make VERBOSE=1 COLOR=0 CONFIG=TestV9
  - make VERBOSE=1 COLOR=0 CONFIG=Othermill
  - make VERBOSE=1 COLOR=0 CONFIG=PrintrbotSimple1608
  - make VERBOSE=1 COLOR=0 CONFIG=sbv300
before_deploy:
  - cd g2core
  - mv bin/Othermill-g2v9k/g2core.elf bin/g2core-Othermill-g2v9k.elf
  - mv bin/Othermill-g2v9k/g2core.bin bin/g2core-Othermill-g2v9k.bin
  - mv bin/PrintrbotSimple1608-printrboardG2v3/g2core.elf bin/g2core-PrintrbotSimple1608-printrboardG2v3.elf
  - mv bin/PrintrbotSimple1608-printrboardG2v3/g2core.bin bin/g2core-PrintrbotSimple1608-printrboardG2v3.bin
  - mv bin/TestV9-g2v9k/g2core.elf bin/g2core-TestV9-g2v9k.elf
  - mv bin/TestV9-g2v9k/g2core.bin bin/g2core-TestV9-g2v9k.bin
  - mv bin/sbv300-sbv300/g2core.elf bin/g2core-sbv300-sbv300.elf
  - mv bin/sbv300-sbv300/g2core.bin bin/g2core-sbv300-sbv300.bin
deploy:
  provider: releases
  # We'll mark these as prerelease, and we can later unmark them by hand.
  # OR, when we move to Master, we remove this setting.
  prerelease: true
  api_key:
    secure: hBB3dHzLM97onnpneoxpewDFYfmcDmeE6FPFRxplaGYROO7SjML8orFCGMLX1cEIlvn4lwzAB+NlE2kreujxiB/gEdZy5DNk8ts+QrbfRXax/VmCNgZYp0tOVn037UFi39rKzx8olbFTImdQypMVf5mdbusY64hTpWrrsZ4uBoU=
  skip_cleanup: true
  file:
    - g2core/bin/g2core-Othermill-g2v9k.elf
    - g2core/bin/g2core-Othermill-g2v9k.bin
    - g2core/bin/g2core-PrintrbotSimple1608-printrboardG2v3.elf
    - g2core/bin/g2core-PrintrbotSimple1608-printrboardG2v3.bin
    - g2core/bin/g2core-TestV9-g2v9k.elf
    - g2core/bin/g2core-TestV9-g2v9k.bin
    - g2core/bin/g2core-sbv300-sbv300.elf
    - g2core/bin/g2core-sbv300-sbv300.bin
  on:
    repo: synthetos/g2
    tags: true
